export const ADMIN_PRODUCT_REVIEW_REQUEST = "ADMIN_PRODUCT_REVIEW_REQUEST";
export const ADMIN_PRODUCT_REVIEW_SUCCESS = "ADMIN_PRODUCT_REVIEW_SUCCESS";
export const ADMIN_PRODUCT_REVIEW_FAIL = "ADMIN_PRODUCT_REVIEW_FAIL";

export const ADMIN_DELETE_PRODUCT_REVIEW_REQUEST = "ADMIN_DELETE_PRODUCT_REVIEW_REQUEST";
export const ADMIN_DELETE_PRODUCT_REVIEW_SUCCESS = "ADMIN_DELETE_PRODUCT_REVIEW_SUCCESS";
export const ADMIN_DELETE_PRODUCT_REVIEW_RESET = "ADMIN_DELETE_PRODUCT_REVIEW_RESET";
export const ADMIN_DELETE_PRODUCT_REVIEW_FAIL = "ADMIN_DELETE_PRODUCT_REVIEW_FAIL";



export const CLEAR_ERRORS = "CLEAR_ERRORS";
