export const SLIDER_REQUEST = "SLIDER_REQUEST";
export const SLIDER_SUCCESS = "SLIDER_SUCCESS";
export const SLIDER_FAIL = "SLIDER_FAIL";

export const SINGLE_SLIDER_REQUEST = "SINGLE_SLIDER_REQUEST";
export const SINGLE_SLIDER_SUCCESS = "SINGLE_SLIDER_SUCCESS";
export const SINGLE_SLIDER_FAIL = "SINGLE_SLIDER_FAIL";

export const CREATE_SLIDER_REQUEST = "CREATE_SLIDER_REQUEST";
export const CREATE_SLIDER_SUCCESS = "CREATE_SLIDER_SUCCESS";
export const CREATE_SLIDER_RESET = "CREATE_SLIDER_RESET";
export const CREATE_SLIDER_FAIL = "CREATE_SLIDER_FAIL";

export const UPDATE_SLIDER_REQUEST = "UPDATE_SLIDER_REQUEST";
export const UPDATE_SLIDER_SUCCESS = "UPDATE_SLIDER_SUCCESS";
export const UPDATE_SLIDER_RESET = "UPDATE_SLIDER_RESET";
export const UPDATE_SLIDER_FAIL = "UPDATE_SLIDER_FAIL";

export const DELETE_SLIDER_REQUEST = "DELETE_SLIDER_REQUEST";
export const DELETE_SLIDER_SUCCESS = "DELETE_SLIDER_SUCCESS";
export const DELETE_SLIDER_RESET = "DELETE_SLIDER_RESET";
export const DELETE_SLIDER_FAIL = "DELETE_SLIDER_FAIL";



export const CLEAR_ERRORS = "CLEAR_ERRORS";
