export const SLIDER_REQUEST = "SLIDER_REQUEST";
export const SLIDER_SUCCESS = "SLIDER_SUCCESS";
export const SLIDER_FAIL = "SLIDER_FAIL";

export const BANNER_REQUEST = "BANNER_REQUEST";
export const BANNER_SUCCESS = "BANNER_SUCCESS";
export const BANNER_FAIL = "BANNER_FAIL";

export const CATEGORY_REQUEST = "CATEGORY_REQUEST";
export const CATEGORY_SUCCESS = "CATEGORY_SUCCESS";
export const CATEGORY_FAIL = "CATEGORY_FAIL";

export const PRODUCT_BY_CATEGORY_REQUEST = "PRODUCT_BY_CATEGORY_REQUEST";
export const PRODUCT_BY_CATEGORY_SUCCESS = "PRODUCT_BY_CATEGORY_SUCCESS";
export const PRODUCT_BY_CATEGORY_FAIL = "PRODUCT_BY_CATEGORY_FAIL";

export const PRODUCT_REQUEST = "PRODUCT_REQUEST";
export const PRODUCT_SUCCESS = "PRODUCT_SUCCESS";
export const PRODUCT_FAIL = "PRODUCT_FAIL";

export const PRODUCT_DETAIL_REQUEST = "PRODUCT_DETAIL_REQUEST";
export const PRODUCT_DETAIL_SUCCESS = "PRODUCT_DETAIL_SUCCESS";
export const PRODUCT_DETAIL_FAIL = "PRODUCT_DETAIL_FAIL";

export const SALE_PRODUCT_REQUEST = "SALE_PRODUCT_REQUEST";
export const SALE_PRODUCT_SUCCESS = "SALE_PRODUCT_SUCCESS";
export const SALE_PRODUCT_FAIL = "SALE_PRODUCT_FAIL";

export const SHOP_PRODUCT_REQUEST = "SHOP_PRODUCT_REQUEST";
export const SHOP_PRODUCT_SUCCESS = "SHOP_PRODUCT_SUCCESS";
export const SHOP_PRODUCT_FAIL = "SHOP_PRODUCT_FAIL";

export const PRODUCT_REVIEW_REQUEST = "PRODUCT_REVIEW_REQUEST";
export const PRODUCT_REVIEW_SUCCESS = "PRODUCT_REVIEW_SUCCESS";
export const PRODUCT_REVIEW_RESET = "PRODUCT_REVIEW_RESET";
export const PRODUCT_REVIEW_FAIL = "PRODUCT_REVIEW_FAIL";

export const PLACE_ORDER_REQUEST = "PLACE_ORDER_REQUEST";
export const PLACE_ORDER_SUCCESS = "PLACE_ORDER_SUCCESS";
export const PLACE_ORDER_RESET = "PLACE_ORDER_RESET";
export const PLACE_ORDER_FAIL = "PLACE_ORDER_FAIL";



export const FUTURE_PRODUCT_REQUEST = "FUTURE_PRODUCT_REQUEST";
export const FUTURE_PRODUCT_SUCCESS = "FUTURE_PRODUCT_SUCCESS";
export const FUTURE_PRODUCT_FAIL = "FUTURE_PRODUCT_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";